version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - '8080:80'

  # Redis service
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  # Elasticsearch service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

  # NestJS app service
  nestjs_app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 123456
      DB_NAME: test
      MAIL_HOST: smtp.gmail.email
      MAIL_USER: ngotienphong053@gmail.com
      MAIL_PASSWORD: vfymtszpryzvqxqd
      MAIL_FROM: noreply@gmail.com

# Define volumes
volumes:
  mysql_data:
